# Build command that Netlify looks for
[build]
  # command = "node ./bin/setup-redirects && node ./bin/build-pub-manifest && vuepress build docs"
  command = "node ./bin/setup-redirects && node ./bin/curl-endpoints && vuepress build docs"

