apiVersion: v1
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  prometheus.yml: |
    scrape_configs:
    - job_name: 'kuma-dataplanes'
      scrape_interval: "5s"
      file_sd_configs:
      - files:
        - /var/run/kuma.io/prometheus-sd/kuma.file_sd.json
  recording_rules.yml: |
    {}
  rules: |
    {}
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-17T16:52:52Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.2
    component: server
    heritage: Helm
    release: my-release
  name: my-release-prometheus-server
  namespace: default
  resourceVersion: "3094"
  selfLink: /api/v1/namespaces/default/configmaps/my-release-prometheus-server
  uid: 2cc41c80-a26e-406e-a5c6-c8af8a7ef11c
